/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/assets/models/tree.glb --instanced 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tree.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials['Material #47']} position={[0.029, -0.005, -0.045]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
      <group position={[0.029, -0.005, -0.045]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008}>
        <mesh geometry={nodes.mesh_1.geometry} material={materials['Material #48']} />
        <mesh geometry={nodes.mesh_1_1.geometry} material={materials['Material #49']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tree.glb')
